@timeout = 5000
@url = http://localhost:3000

GET {{url}}/employees/
###

GET {{url}}/employees/2bd79698273579b8288f

###
POST {{url}}/employees/
Content-Type: application/json

{
    "name": "John",
    "position": "Manager",
    "salary":50000,
    "other": "stuff"
}